[package]
name = "cumulus-primitives-utility"
version = "0.1.0"
authors = ["Elexeum <info@elexeum.org>"]
edition = "2021"

[dependencies]
# Substrate dependencies
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16", default-features = false }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16", default-features = false }

# Elexeum dependencies
elexeum-parachain = { path = "../../../../modules/parachain", default-features = false }
elexeum-primitives = { path = "../../../../primitives", default-features = false }
elexeum-core-primitives = { path = "../../../../primitives/core-primitives", default-features = false }
xcm = { path = "../../../../modules/xcm", default-features = false }

cumulus-primitives-core = { path = "../core", default-features = false }

# Other dependencies
codec = { package = "parity-scale-codec", version = "2.3.0", default-features = false, features = [ "derive" ] }


[features]
default = [ "std" ]
std = [
	"codec/std",
	"sp-std/std",
	"elexeum-primitives/std",
	"elexeum-parachain/std",
	"elexeum-core-primitives/std",
	"sp-runtime/std",
	"sp-trie/std",
	"frame-support/std",
	"cumulus-primitives-core/std",
]
