[package]
name = "elexeum-cli"
version = "0.2.1"
authors = ["Elexeum <info@elexeum.org>"]
description = "Elexeum Relay-chain Client Node"
edition = "2018"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on Linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.13"
thiserror = "1.0.30"
structopt = { version = "0.3.25", optional = true }
futures = "0.3.19"

service = { package = "elexeum-service", path = "../../node/service", default-features = false, optional = true }
elexeum-node-core-pvf = { path = "../../../system-node/core/pvf", optional = true }
elexeum-performance-test = { path = "../../node/test/performance-test", optional = true }
elexeum-node-metrics = { path = "../../../system-node/metrics" }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16", optional = true }
try-runtime-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16", optional = true }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16", optional = true }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16", optional = true }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16", optional = true }

# this crate is used only to enable `trie-memory-tracker` feature
# see https://github.com/paritytech/substrate/pull/6745
sp-trie = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false}

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }

[features]
default = [ "wasmtime", "db", "cli", "full-node", "trie-memory-tracker", "elexeum-native" ]
wasmtime = [ "sc-cli/wasmtime" ]
db = [ "service/db" ]
cli = [
	"structopt",
	"sc-cli",
	"sc-service",
	"sc-tracing",
	"frame-benchmarking-cli",
	"try-runtime-cli",
	"elexeum-node-core-pvf",
	"elexeum-performance-test",
]
runtime-benchmarks = [ "service/runtime-benchmarks", "elexeum-node-metrics/runtime-benchmarks" ]
trie-memory-tracker = [ "sp-trie/memory-tracker" ]
full-node = [ "service/full-node" ]
try-runtime = [ "service/try-runtime" ]
fast-runtime = [ "service/fast-runtime" ]

# Configure the native runtimes to use. elexeum is enabled by default.
#
# Validators require the native runtime currently
elexeum-native = [ "service/elexeum-native" ]
cardamom-native = [ "service/cardamom-native" ]

runtime-metrics = ["service/runtime-metrics", "elexeum-node-metrics/runtime-metrics"]
