[package]
name = "elexeum-statement-distribution"
version = "0.2.1"
authors = ["Elexeum <info@elexeum.xyz>"]
description = "Statement Distribution Subsystem"
edition = "2018"

[dependencies]
futures = "0.3.19"
tracing = "0.1.29"
elexeum-primitives = { path = "../../../primitives" }
sp-staking = { git = "https://github.com/paritytech/substrate",branch = "polkadot-v0.9.16", default-features = false}
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
elexeum-subsystem = { package = "elexeum-node-subsystem", path = "../../subsystem" }
elexeum-node-primitives = { path = "../../primitives" }
elexeum-node-subsystem-util = { path = "../../subsystem-util" }
elexeum-node-network-protocol = { path = "../../network/protocol" }
arrayvec = "0.5.2"
indexmap = "1.7.0"
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
derive_more = "0.99.17"
thiserror = "1.0.30"

[dev-dependencies]
elexeum-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
assert_matches = "1.4.0"
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
futures-timer = "3.0.2"
elexeum-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
